### ISSUE TITLE
Groovy home is wrong for version 2.4.6

### ISSUE THREAD

**Issue by sideris** [groovy/groovy-windows-installer#1] opened 2016-05-30 01:19 UTC
I tried to do `groovy -v` but it couldn't find it. I checked the variable set and it was 

`C:\PROGRA~\GROOVY.1.6~` if I remember well (changed it before thinking to raise this here)

I changed the default directory from `Program Files (x86) to`Program Files` during installation

**Comment by keeganwitt** [comment] 2016-06-01 04:54
I'm not ignoring you.  I'll try to check into this tomorrow.

**Comment by keeganwitt** [comment] 2016-06-02 00:18
I'm having trouble recreating this.  What did you see in the "Create GROOVY_HOME" field when you ran the installer?  And if Groovy was previously installed, did you uninstall the earlier version before running the installer again?

**Comment by sideris** [comment] 2016-06-02 11:46
Wasn't installed with an installer, had manually added it to the `Path` variable. I can't recall but let me try this again.

FYI I am on Windows 10 Pro and as I said I changed the path from `x86` Program files to the regular. Also, I had Grails installed but I don't think they had set any env variable because I couldn't `groovy`

**Comment by sideris** [comment] 2016-06-02 11:57
![capture](https://cloud.githubusercontent.com/assets/5484694/15744047/8121fd92-28c1-11e6-8a82-5d930f8ba575.PNG)

I have a video as well

**Comment by sideris** [comment] 2016-06-05 00:53
When I say wasn't installed with an installer I mean beforehand. I had downloaded the zip. Then used the installer to update after I deleted the variables and then I noticed the issue

**Comment by keeganwitt** [comment] 2016-06-06 20:30
Were these system or user variables?  The installer will only update the system variables and wouldn't overwrite any user variables you had previously set when using zip archive.

**Comment by sideris** [comment] 2016-06-06 22:39
System

**Comment by keeganwitt** [comment] 2016-06-19 18:59
Were you running this with silent flag?  #3 was just opened that pointed out this issue.

**Comment by sideris** [comment] 2016-06-19 23:16
Probably, don't really remember

**Comment by keeganwitt** [comment] 2020-02-04 23:45
Closing for now. We can re-open if the issue is still occurring.

**Closed as completed by keeganwitt** 2020-02-04 23:45 UTC
